# Common settings for both environments
spring.profiles.active=${ACTIVE_PROFILE:local}

# JPA Common
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Thymeleaf Common
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Logging Common
logging.level.org.springframework.web=INFO

# Server
server.error.include-message=always